run:
  deadline: 5m
  modules-download-mode: vendor

linters:
  fast: false
  enable-all: true
  disable:
    - gomnd
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - lll
    - unparam
    - funlen
    - wsl

linters-settings:
  gocognit:
    # cognitive complexity 78 of func `resourceMKSClusterV1Update` is high (> 30) (gocognit)
    min-complexity: 78
