run:
  deadline: 5m
  modules-download-mode: vendor

linters:
  fast: false
  enable-all: true
  disable:
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - lll
    - unparam
    - funlen
