sudo: false
language: go
go:
  - "1.14.x"
services:
  - "docker"
env:
  - GOFLAGS=-mod=vendor GO111MODULE=on

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.1

script:
  - make test
  - make lintcheck
  - make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
