name: Acceptance Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Run test
        run: make testacc
        env:
          GO_FLAGS: -mod=vendor
          GO111MODULE: on
          SEL_TOKEN: ${{ secrets.SEL_TOKEN }}

