name: Acceptance Tests
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Run test
        run: make testacc
        env:
          OS_DOMAIN_NAME: ${{ secrets.OS_DOMAIN_NAME }}
          OS_USERNAME:    ${{ secrets.OS_USERNAME }}
          OS_PASSWORD:    ${{ secrets.OS_PASSWORD }}
