name: Acceptance Tests
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * *'

jobs:
  accepance-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Run test
        run: make testacc
        env:
          GO_FLAGS: -mod=vendor
          GO111MODULE: on
          TF_LOG: debug
          SEL_TOKEN: ${{ secrets.SEL_TOKEN }}

